####################################yukmg######################################

####################################kimkc######################################

####################################kimmin######################################
/link_2.biz=kimmin.controller.Link_2
####################################junyj######################################

####################################kimth######################################