####################################yukmg######################################
/index.biz=yukmg.controller.YukmgCtrl
####################################kimkc######################################
/kimkc.biz=kimkc.controller.KimkcController
####################################kimmin######################################
/link_2.biz=kimmin.controller.Link_2
####################################junyj######################################
/link_3.biz=jungyj.controller.Link_3
####################################kimth######################################
/link_4.biz=kimth.controller.Link_4