####################################yukmg######################################

####################################kimkc######################################

####################################kimmin######################################

####################################junyj######################################
/link_3.biz=jungyj.controller.Link_3
####################################kimth######################################